# arange

In [4]:
import numpy as np

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# zeros

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

# ones (tüm eleman 1)

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((9,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

# linspace (parametreler arası eşit boşluk)

In [14]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [15]:
# 0 ve 20 arasında 5 eşit parça

In [16]:
np.linspace(0,20,7)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        ])

# eye (birim matris)

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#birim matris

# random

In [19]:
np.random.randn(8)

array([-0.66517203,  0.56727697,  0.69771576,  0.09255217,  0.01963751,
       -0.65351674, -0.20365021, -1.03497334])

In [20]:
np.random.randn(3,3)

array([[-0.05052995, -1.30497749, -0.22974412],
       [ 0.87574864,  0.75553298,  2.11428245],
       [ 0.43291984,  0.23909401, -0.25392331]])

In [21]:
np.random.randint(1,10)

8

In [22]:
np.random.randint(1,10,8)

array([4, 7, 8, 1, 6, 5, 9, 9])

In [23]:
numpyDizi=np.arange(30)

In [24]:
numpyDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
numpyRandomDizi=np.random.randint(0,100,20)

In [26]:
numpyRandomDizi

array([16, 36, 83, 82, 99, 77,  5,  2,  3, 96, 52, 22, 18, 58, 74, 39, 77,
       81, 87, 96])

## numpy dizi metodları

In [27]:
numpyDizi.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
numpyDizi.max()

29

In [29]:
numpyDizi.min()

0

In [31]:
numpyDizi.argmax()  #max değerli sayının olduğu index

29

In [33]:
numpyDizi.shape

(30,)

In [34]:
reshapeDizi=numpyDizi.reshape(5,6)
reshapeDizi.shape

(5, 6)

## random integer matris

In [10]:
np.random.randint(100, size=(2, 4))

array([[69, 49, 81, 57],
       [52,  5, 90, 14]])